### ISSUE TITLE
shouldn't appCommandGsUtil be a boolean?

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-tools-lib-for-java#102]

**Comment by meltsufin** [comment]
I believe the only possible values are 0 or 1. So, yes, I think it should be a boolean.

**Comment by patflynn** [comment]
actually it occurs to me that our credential flow doesn't even work with the gsutil based flow?  Should we even give clients the option of using it?

**Comment by meltsufin** [comment]
I think this property was added on request by Etan. @etanshaul do you remember what it was for?

**Comment by etanshaul** [comment]
Yes we use gsutil to control how the credentials are loaded. A value of 0 indicates that we are not loading them from gcloud - we use this in conjunction with the credential override file which we pass into gcloud.

**Comment by etanshaul** [comment]
@patflynn isn't it possible that some clients of app-tools may want to use the gsutil based credential flow?

**Comment by patflynn** [comment]
Actually thinking about it further, I think it is possible for now.  How
about we simply set the non-gsutil path when overriding the credentials?

**Comment by etanshaul** [comment]
I like that approach myself since they will always (I think) be used together like that.
