### ISSUE TITLE
app-tools-lib-for-java is not a great name

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-tools-lib-for-java#108]
the name combines verbosity with ambiguity.  

Additionally naming for the artifact is a bit weird.  Most Maven artifacts don't need to -for-java as a suffix. All Maven artifacts are for Java. Perhaps the github repo name doesn't need to be the same as the artifact id? 

This issue is to track that we are happy with the naming of the github project and artifactId prior to GA.

**Comment by meltsufin** [comment]
@patflynn  appengine-tools? and it will appear as appengine-tools.jar in the repositories?

**Comment by loosebazooka** [comment]
this is fixed, decided on appengine-plugins-core
