### ISSUE TITLE
Restore CloudSdk#validate() to check a location

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/app-tools-lib-for-java#118]
`CloudSdk` had a `validate()` method to check whether the location seemed like a real installation.  This check is useful for handling user-configured locations.

**Comment by elharo** [comment]
https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/blob/557b9e787b6f8c13f4b87969dc1a69b27d78453c/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/runtime/CloudSdkRuntime.java

**Comment by briandealwis** [comment]
There was a validate() in a previous version that checked that some key files and directories were found in the right place (e.g., `bin/gcloud`, `bin/dev_appserver.py`).  We don't want to duplicate that logic.

**Comment by meltsufin** [comment]
Yes, we can put it back in.
