### ISSUE TITLE
The JVM flags are incorrectly set for the dev app server run command

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/app-tools-lib-for-java#121]
When adding the arguments to the dev app server run command, the jvm flags are set as "--jvm_flag -Dappengine.user.timezone=UTC" instead of "--jvm_flag=-Dappengine.user.timezone=UTC", which causes the following error:

usage: dev_appserver.py [-h] [-A APP_ID] [--host HOST] [--port PORT]
                        [--admin_host ADMIN_HOST] [--admin_port ADMIN_PORT]
                        ...
                        yaml_or_war_path [yaml_or_war_path ...]
dev_appserver.py: error: argument --jvm_flag: expected one argument

**Comment by loosebazooka** [comment]
I think we do this, what build are you working off of?

**Comment by loosebazooka** [comment]
Weird, It looks like this does accept `=`. We can probably change this to be `=` instead of ` `

**Comment by meltsufin** [comment]
The help page for dev_appserver.py shows this syntax:
```
[--jvm_flag JVM_FLAG]
```
Which is what the library seems to be doing by separting name and value with a space, not an `=`.

I wonder if you really should be passing in `appengine.user.timezone=UTC` as a value, instead of the `-Dappengine.user.timezone=UTC`.

**Comment by nbashirbello** [comment]
Passing appengine.user.timezone=UTC causes the following error:

Error: Could not find or load main class appengine.user.timezone=UTC

**Comment by briandealwis** [comment]
@nbashirbello Just to be sure, how are you passing in the arguments?  `CloudSdk` takes an array of args, so that should be sent as: `new String[] { …, "--jvm_flag", "-Dxxx", "--jvm_flag", "-Xdebug", … }`

@meltsufin in this case, the property is a [workaround](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/issues/181) for running the `dev_appserver` on Java 8.  Ideally it shouldn't be necessary.  But we will need to pass JVM flags to configure JVM debug flags (e.g., `-Xdebug -agentlib:jdwp=transport=dt_socket,server=n,address=37632`)

**Comment by meltsufin** [comment]
You should be using `CloudSdkAppEngineDevServer.run(RunConfiguration config)` to run the dev app server. `CloudSdk.runDevAppServerCommand()` should not be used directly.
If you're using `DefaultRunConfiguration`, there is a method there to set the jvm flags:
```java
  public void setJvmFlags(List<String> jvmFlags) {
    this.jvmFlags = jvmFlags;
  }
```

That being said, if there is a workaround for making the dev app server run on Java 8, it should be integrated into the library instead.

**Comment by meltsufin** [comment]
.... if not into the actual dev_appserver.py

**Comment by briandealwis** [comment]
…or fixed in the `DevAppServer2Impl`

**Comment by nbashirbello** [comment]
I am using DefaultRunConfiguration#setJvmFlags and AppEngineDevServer#run

**Comment by meltsufin** [comment]
Despite the usage page for dev_appserver.py, I think @nbashirbello is correct about the use of `=`. Will work on a fix.
