### ISSUE TITLE
Failures on Windows

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/app-tools-lib-for-java#129]
Paths that have spaces are causing commands to fail on Windows.
Dev App Server 'run' command fails due to Python not being installed on Windows.

**Comment by patflynn** [comment]
Even with the Cloud SDK installed?

**Comment by meltsufin** [comment]
Well, there is a bundled python.exe in the Cloud SDK, which we'll use in the fix. It's not added to PATH automatically though, and you can't execute *.py files directly on Windows.
