### ISSUE TITLE
Detect Cloud SDK location when not installed into google-cloud-sdk

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/app-tools-lib-for-java#131]
Currently, if the Cloud SDK is not installed into a 'google-cloud-sdk' directory, but is added to the PATH, it will not be discovered by PathResolver.

**Comment by meltsufin** [comment]
Closing because 'google-cloud-sdk' is a fairly standard location.

**Comment by briandealwis** [comment]
I'd like to re-open this as I had the same thought and think it would be a great idea.

I actually manage most non-package installations like GCSDK by installing them in a versioned directory like `/usr/local/installs/google-cloud-sdk-110.0` and then symlinking appropriate `bin/` file into `/usr/local/bin`.  Saves my sanity.

We could check for `gcloud` and `gcloud.cmd` on the PATH, and use `Files.isSymbolicLink()` and `Files.readSymbolicLink()` to handle these types of cases.  We'd need to move the `CloudSdk.validate()` logic, perhaps to a static method.  That would actually be useful for the Eclipse tooling to support [validating user choices](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/issues/231).

**Comment by meltsufin** [comment]
OK, sounds good.

**Comment by loosebazooka** [comment]
@briandealwis can we close this bug?

**Comment by briandealwis** [comment]
The Eclipse resolver satisfies my needs, so let's close and re-open if required in the future.
