### ISSUE TITLE
PathResolver should implement an interface to enable mocking

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/app-tools-lib-for-java#149]
PathResolver is an enum and as such cannot be mocked, but it would be helpful to write unit tests that are independent of the executing environment.

**Comment by elharo** [comment]
That sounds like epicycles on epicycles to me. If being an enum is a problem, just make it a class.

**Comment by akerekes** [comment]
@elharo I believe it's enum to make it singleton without the necessary synchronization and locking.

**Comment by elharo** [comment]
But as soon as you make it an interface it's no longer a singleton. There can be other implementations.

**Comment by meltsufin** [comment]
Have you considered an alternative to mocking the `PathResolver`? Maybe hide it behind one of your own interfaces, and then mock that interface.

That being said, I don't see a problem with creating a `PathResolver` interface and a `DefaultPathResolver` implementation in the library to help with testing and potentially allow other implementations.

**Comment by akerekes** [comment]
@meltsufin yeah, that's definitely a valid option. However since this library is mostly under our control, it seems easier to make changes to it than wrapping it in other projects (whereas if it was a third party library I'd definitely go with the wrapping approach).
