### ISSUE TITLE
Provide hooks for locating the Google Cloud SDK in other locations

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/app-tools-lib-for-java#169]
When an explicit location has not been specified, `CloudSdk.Builder` uses `PathResolver` to try to discover the location of the Google Cloud SDK based on a set of heurstics by looking in a few fixed locations and examining the directories on the `PATH`, or specified in `GOOGLE_CLOUD_SDK_HOME`.  Many developers work on locked-down machines, or manage their disk layouts in different fashions.  For example, many Unix users put installations under `/opt`.  Some package managers consider `/usr/local` to be their own managed area.  There is much evidence that many developers struggle to change their `PATH`.

So for the Eclipse tooling, we provide the user means to configure the locations through a preference page ([issue](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/issues/231), [commit](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/pull/255)).  This solution requires our code to use two new classes to fetch a `CloudSdk` instance rather than use the library's `Cloudsdk.Builder` directly:
  - `CloudSdkProvider` is a factory that uses the user preference to set `CloudSdk.Builder#sdkPath()`, and otherwise delegates to `PathResolver`
  - `CloudSdkPrompter` is like `CloudSdkProvider` but will prompt the user if the preference is unset and `PathResolver`  is unable to find the SDK

The downside to this solution is that we must be vigilant and stamp out any use of `CloudSdk.Builder` and convert the code to use our `CloudSdkProvider` or `CloudSdkPrompter` instead.  Otherwise we risk the SDK not being found _despite the user preference_.  We've already hit occasions where someone has committed code that uses `new CloudSdk.Builder().build()` instead of our `CloudSdkProvider` and thus caused breakage.  This is somewhat less than optimal.

It could be argued that `PathResolver`'s heuristics should be improved by specifying additional locations.  But I don't think we can possibly satisfy everyone.  And this doesn't help the poor developer who uses yet another different location that we haven't supported until now.

I propose that `CloudSdk.Builder` instead support a mechanism to provide additional path resolvers for locating the Google Cloud SDK.  We would then rewrite the Eclipse `CloudSdkProvider` as such a resolver.  Ideally this mechanism should not require any changes for the consumers of the library, such that they can continue to simply call `new CloudSdk.Builder().build()`.

**Comment by briandealwis** [comment]
See also #131

**Comment by elharo** [comment]
How does CloudSdkPrompter talk to the user? This library cannot assume there is a user.
