### ISSUE TITLE
Should AppEngineSdk be merged with CloudSdk?

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/app-tools-lib-for-java#20]
Since App Engine SDK can now be bundled with Cloud SDK, there doesn't seem to be a need for the users to provide a Cloud SDK path and an App Engine SDK path separately. That being the case, should we just merge AppEngineSdk with CloudSdk, and simply move the AppEngineSdk.runCommand() to CloudSdk?

**Comment by meltsufin** [comment]
@loosebazooka @patflynn

**Comment by patflynn** [comment]
what does 'can now be bundled..' mean?

**Comment by meltsufin** [comment]
gcloud components install app-engine-java

**Comment by patflynn** [comment]
That's not the whole sdk though. At least it's not intended to be.  It
probably should be, but we should get the Cloud SDK and the Java App Engine
SDK to commit to that,

**Comment by meltsufin** [comment]
We only need the part for staging App Engine standard apps at this point.

**Comment by meltsufin** [comment]
From the offline conversations, it sounded like we can rely on the staging parts to be in the Cloud SDK in the foreseeable future. Is that correct? @patflynn

**Comment by patflynn** [comment]
@meltsufin yeah I think so
