### ISSUE TITLE
Use appcfg directly from the sdk reference instead of using a maven dependency

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/app-tools-lib-for-java#30]
see https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/blob/master/src/main/groovy/com/google/appengine/task/appcfg/AppConfigTaskTemplate.groovy#L73

This way we don't have to update the maven dependency like we are in #29

**Comment by meltsufin** [comment]
Is the concern just the need to update the dependency version?

**Comment by loosebazooka** [comment]
Yeah it happens a lot and could be out of sync with a user's cloud sdk
version

**Comment by meltsufin** [comment]
I see. I think we can change the dependency to 'provided' and then dynamically load from the SDK.

**Comment by loosebazooka** [comment]
Ideally we wouldnt have the dependency at all in our pom
