### ISSUE TITLE
make sure we allow setting the environment variable to identifying the deployment source

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/app-tools-lib-for-java#39]

**Comment by etanshaul** [comment]
We may want to either expand this to handle the general case of arbitrary environment variables, or add other known ones we'd want to support here too.

For example: 
CLOUDSDK_METRICS_ENVIRONMENT
CLOUDSDK_APP_USE_GSUTIL

**Comment by etanshaul** [comment]
On second thought, arbitrary environment variables could be set on the ProcessBuilder by the caller. I'm thinking we should just expose a convenience method to allow clients to set the calling source (not just for deployment but for any action), which may be more inline with what was intended by this.

**Comment by loosebazooka** [comment]
I'm thinking about updating the cloud sdk builder to hide all of the underlying processbuilder stuff. So this would just be another cloud sdk builder parameter.

**Comment by etanshaul** [comment]
oh ok. then I won't rely on the client having correctly set it on the processbuilder.

**Comment by loosebazooka** [comment]
Well the client just has to set it on the sdk

**Comment by meltsufin** [comment]
@loosebazooka What do you mean about hiding the processbuilder stuff? Currently we only expose the ability to set a ProcessRunner, and if none is set, we create the DefaultProcessRunner that itself uses a ProcessBuilder.

I do agree about it being another parameter. Are you thinking of a generic `Builder.envVariable(name, value)` or specific `Builder.metricsEnvironment(value)` and `Builder.useGsUtil()`?

**Comment by chanseokoh** [comment]
FYI, in addition to the above two env variables, we will add one more:

CLOUDSDK_METRICS_ENVIRONMENT_VERSION

I don't see any need for special handling, but just in case, please make sure those env variables work on Mac and Windows too.
