### ISSUE TITLE
Allow clients to destroy the running process

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/app-tools-lib-for-java#57]
Both for sync or async.

Need to expose ability to kill a process that was started for consumers using a custom ProcessRunner.

**Comment by meltsufin** [comment]
I wonder if we should change the ProcessRunner.run signature to return Process instead of void. This would also free us from dealing with sync vs async because the client would be responsible for calling process.waitFor().

**Comment by etanshaul** [comment]
I was thinking about this, but this causes the Process to trickle up to the SDK and up to the actions (deploy etc.) which doesn't seem ideal.

Another option is to restrict the default ProcessRunner to a single process (or create a new type). This way a cancel() method can be added and it can take care of destroying itself.

**Comment by meltsufin** [comment]
The SDK doesn't really do much with the ProcessRunner. I'm almost tempted to take the whole ProcessRunner concern out of the SDK and change the runCommand*(args) to List<String> getCommand*(args).

Of course, we can also just expose the Process in the DefaultProcessRunner by adding a getCurrentProcess() method.

**Comment by etanshaul** [comment]
I think its still nice for clients that don't want to concern themselves with running the process to not have to deal with the ProcessRunner at all and let the sdk create the default one and run the command.

Regarding your second point - what if the client triggers multiple actions using the same sdk instance?

**Comment by meltsufin** [comment]
With the build plugins, we're always creating a new CloudSdk for each execution. So, it's not a concern. However, I see how your point applies to stafeful IDE plugins. We can mitigate this by making sure that the DefaultProcessRunner only executes one process at a time.

**Comment by etanshaul** [comment]
Sure. But then if it only executes one process at a time, couldn't you also go ahead and just add the destroy functionality for this PR right into the DefaultProcessRunner? e.g. DefaultProcessRunner#destroyProcess() or something.

**Comment by meltsufin** [comment]
Yes, but I thought it would be nice to also support other usecases that need to operate on the Process. For example, someone might want direct access to the process in/out streams.

**Comment by etanshaul** [comment]
Ah. I see, yea that could be useful.
