### ISSUE TITLE
When staging for standard environment, do not attempt to copy Dockerfile if it doesn't exist

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/app-tools-lib-for-java#63]

**Comment by loosebazooka** [comment]
I'm not sure I understand this error. But if a user defines a dockerfile, shouldn't we inform them that it doesn't exist instead of continuing silently?

**Comment by meltsufin** [comment]
That's a good question. In Maven, we set up a default Dockerfile location, and it may not exist. We can also check if there is a file in the default location in the plugin, and pass null in that case. However, in CloudSdkAPpEngineFlexibleStaging we do check if the Dockerfile exists before copying it. So, I wanted to do the same for standard.

**Comment by loosebazooka** [comment]
Oh yeah huh. I wonder if we should just define the default values for everything in the common lib? We can then validate user overrides?

**Comment by meltsufin** [comment]
Some defaults are plugin-specific. For example, dockerfile is ${basedir}/src/main/appengine/Dockerfile in Maven.

**Comment by loosebazooka** [comment]
oh yeah good point
