### ISSUE TITLE
Provide default configuration implementations for every action

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/app-tools-lib-for-java#7]
Package com.google.cloud.tools.app.config contains interfaces for each action's configuration.

Maven and Gradle will have implementations of their own, but the library should provide a default implementation for other clients which don't have any implementation. These implementations should probably use builder syntax.

e.g., DefaultDeleteConfigurationImpl.newDeleteConfiguration(requiredParam1, requiredParam2)
  .optionalParam1(p1)
  .optionalParam2(p2)

**Comment by joaoandremartins** [comment]
I also just noticed that unit tests are going to depend on these implementations being available.

I provided a sample default implementation in #1 called DefaultStageGenericJavaConfigurationImpl. The others should follow the same pattern.

For now, unit tests are almost all failing.

**Comment by meltsufin** [comment]
done in package com.google.cloud.tools.app.impl.config
