### ISSUE TITLE
For staging with dockerfile, dockerfile must be in exploded-war directory

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/app-tools-lib-for-java#74]

**Comment by meltsufin** [comment]
To clarify, this is for standard compat staging. The dockerfile has to be in the root of the staging directory before running AppCfg staging.

**Comment by loosebazooka** [comment]
Root of the "source" directory.

**Comment by meltsufin** [comment]
Ah! In the terminology of the library, I think it's the staging "Source Directory".
