### ISSUE TITLE
Ensure integration tests pass

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/app-tools-lib-for-java#8]
Identified scenarios that require validation:

Deploy normal Maven app with web.xml (guestbook)
Deploy normal Maven app with vm=true in appengine-web.xml (guestbook)
Deploy pure Java8 app without appengine-web.xml (sparkjava)
Deploy JAR and WAR apps, with/without appengine-web.xml
Test on Windows
Test with no authentication in gcloud
Test with no project set in gcloud
Test without gcloud

We could also test these scenarios in bugouts and new releases.

**Comment by loosebazooka** [comment]
Integration tests are handled by maven/gradle

Our biggest test suite currently at : https://github.com/loosebazooka/appengine-scenarios

Please open a new bug if we aren't covering everything.
