### ISSUE TITLE
Look for Dockerfile in src/main/webapp/ by default for Compat projects

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/app-tools-lib-for-java#95]

**Comment by patflynn** [comment]
Hey Mike,

Can you create equivalent bugs for Eclipse and IntelliJ?

**Comment by meltsufin** [comment]
If they use this lib, shouldn't they inherit the fix automatically.

**Comment by patflynn** [comment]
can it be configured to be somewhere else? I suspect there's going to be UI
involved.

**Comment by meltsufin** [comment]
I think this may actually not require any fix at all. Since the file is in src/main/webapp, it will be in the exploded war and will be copied automatically into the staging directory.

**Comment by meltsufin** [comment]
Confirmed that it works as is. Closing.
