### ISSUE TITLE
Copy all App Engine supported files from src/main/appengine for staging

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/app-tools-lib-for-java#96]
...Not just app.yaml

**Comment by patflynn** [comment]
Are you sure? /src/main/appengine is not creating a 'context' the way a
docker root is supposed to.  Also looking at Ray's last email I'm starting
to question the validity of copying all of docker into the staging
directory.

**Comment by meltsufin** [comment]
I'm not sure, actually. I based this on the comment from Salmaan. But now I'm thinking that he meant the Docker-related files, when Dockerfile is in the appengine directory.

I think we should hold working on this until we get it all cleared up.

**Comment by meltsufin** [comment]
So, we've made the decision to copy all *known and supported* App Engine configuration files from src/main/appengine. If any other files are found in the directory, including the Dockerfile, we'll throw an error asking the user to remove the unsupported files. In the case of the Dockerfile, we'll instruct them to move the file under the src/main/docker folder.

**Comment by meltsufin** [comment]
@arouzrokh Do you have a list of all supported App Engine config files that can go into 'src/main/appengine'?

**Comment by arouzrokh** [comment]
Let's take a step back. Assuming that we copy all files excluding the Dockerfile and know Docker related files (since they have to live in the docker folder), we'd be covering ourselves against all scenarios. Can you describe the reason behind this requirement?

**Comment by meltsufin** [comment]
I don't think we can know what all of the Docker-related files are. Hence, we took the whitelisting approach. We do, however, provide a special error message if we find Dockerfile in the appengine directory.
