### ISSUE TITLE
Project flag needs to be available for all commands

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/app-tools-lib-for-java#97]
This parameter spans multiple commands. While it probably doesn't apply to _all_ commands, I think it should be available to all of them in the same way that `format` is.

**Comment by meltsufin** [comment]
`format` is something we set on the `CloudSdk`. I don't think we want to do the same thing with `project`, which probably belongs in the `*Configuration` classes.

**Comment by etanshaul** [comment]
sure. with that approach (given the current design) we'd be adding to multiple places unless we introduce a new base class.

**Comment by meltsufin** [comment]
base interface should be fine
